# Generated by Django 5.1.2 on 2024-10-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_ast', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='operands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rules')),
            ],
        ),
    ]
