# Generated by Django 5.1.2 on 2024-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='rule_string',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
