# Generated by Django 5.1.2 on 2024-10-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rules_rule_string'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operands',
        ),
    ]
